### ISSUE TITLE
dataset question

### ISSUE THREAD

**Issue by chengm0-0** [zyqz97/PPF_Point-Pair-Feature_cpp#1]
你好，我想请问一下数据集txt文件中每一列代表了什么信息？如果我要采用ply文件需要如何修改呢？以及最后输出的out.txt又代表了什么呢？非常感谢！

**Comment by zyqz97** [comment]
txt文件存储了点坐标及法矢信息，包括x, y, z, nx, ny, nz（输出out.txt也是如此）。ply文件可以使用PCL对代码中的ReadPLY部分进行修改。

**Comment by zyqz97** [comment]
@chengm0-0  txt文件存储了点坐标及法矢信息，包括x, y, z, nx, ny, nz（输出out.txt也是如此）。ply文件可以使用PCL对代码中的ReadPLY部分进行修改。
