### ISSUE TITLE
Code Run Error

### ISSUE THREAD

**Issue by Yfanmeng** [zyqz97/PPF_Point-Pair-Feature_cpp#2]
Dear Author.
        Thanks for the open source code, but I'm having the following problem when I run your code
![1](https://github.com/zyqz97/PPF_Point-Pair-Feature_cpp/assets/115934943/ff5ff1a1-841b-458d-b719-26c646b7ef20)
I have searched for solutions on the internet and have not been able to solve it. How can I solve this problem? Looking forward to your reply.

**Comment by zyqz97** [comment]
So sorry for that. This codebase have been released a few years, so I don't remember the details. I recommend debugging the code from scratch, because it may have a lot of bugs.

**Comment by Yfanmeng** [comment]
> So sorry for that. This codebase have been released a few years, so I don't remember the details. I recommend debugging the code from scratch, because it may have a lot of bugs.

That's fine. Thanks for the reply.
